services:
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: Apache-Kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  vault-server:
    image: hashicorp/vault
    container_name: Vault
    ports:
      - "8200:8200"
    volumes:
      - vault-data:/vault/data
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    restart: always
  init-vault:
    image: hashicorp/vault
    depends_on:
      - vault-server
    command: >
      sh -c "
      sleep 15;
      export VAULT_ADDR=http://vault-server:8200;
      export VAULT_TOKEN=myroot;
      vault secrets enable -path=secret kv-v2 || true;
      vault kv put secret/myapp username_transaction_DB=root password_transaction_DB=0986341885dai masterAccount=970452999999999
      provider.api.electricity.url=http://localhost:8089/mock-api/electricity provider.api.telephone.url=http://localhost:8089/mock-api/telephone
      core-banking.api.url=http://localhost:8083/corebanking/api/core-bank mock-provider-api=http://localhost:8089/mock-api
      mock-napas-api=http://localhost:8089/mock-napas;
      "

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeperRegistry
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://host.docker.internal:3307/keycloak?useSSL=false&serverTimezone=UTC
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=0986341885dai
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY=edge
    ports:
      - "8081:8080"
    command:
      - start-dev
volumes:
  vault-data:
  redis-data:
  #networks:
  #  temporal-network:
  #    driver: bridge