spring.application.name=customer-service

spring.datasource.url=jdbc:mysql://localhost:3306/customerdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
#spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

# Swagger Configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ========== MESSAGES / I18N ==========
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.default-locale=en


## ========== JWT ==========
#jwt.expiration=2592000
#jwt.expiration-refresh-token=5184000
#jwt.secretKey=2bBXzdplW1CbCQqvzmHApdmM91XrxbrJqtgUfQJSEWk=

# Keycloak Configuration
keycloak.auth-server-url=http://localhost:8081
keycloak.realm=${idp_realm}
keycloak.resource=${idp_client_id}
keycloak.bearer-only=false

# Spring Security JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/myrealm

# Keycloak Admin Client
idp.url=http://localhost:8081
idp.realm=${idp_realm}
idp.client-id=${idp_client_id}
idp.client-secret=${idp_client_secret}

server.port=8080

#account-service.url=http://localhost:8082/api/account

#dubbo.application.name=customer-service-consumer
#dubbo.protocol.name=dubbo
#dubbo.protocol.port=20883
#dubbo.registry.address=zookeeper://localhost:2181
#dubbo.scan.base-packages=com.example.customer_service.controllers

# Dubbo Application Configuration
dubbo.application.name=customer_service
dubbo.application.metadata-type=remote
dubbo.application.parameters.dubbo.mapping.cache.file=C:/Users/thienvy/.dubbo/customer-service-cache
dubbo.application.serialization.security.allowlist=file:security/serialize.allowlist
# Dubbo Protocol Configuration
dubbo.protocol.name=dubbo
dubbo.protocol.port=20889
dubbo.application.qos-enable=true
dubbo.application.qos-port=33333
# Dubbo Registry Configuration
dubbo.registry.address=zookeeper://${DOCKER_HOST:localhost}:2181
dubbo.scan.base-packages=com.example.customer_service.service,com.example.customer_service.controllers

# Redis
spring.cache.type=redis
spring.data.redis.host=${DOCKER_HOST:localhost}
spring.data.redis.port=6379
spring.data.redis.password=${redis_password}
spring.cache.redis.cache-null-values=true

spring.cloud.stream.kafka.binder.brokers=${DOCKER_HOST:localhost}:9094

spring.cloud.stream.bindings.mail-register-out-0.destination=sentOtpRegister
spring.cloud.stream.bindings.mail-register-out-0.content-type=application/json

spring.cloud.stream.bindings.mail-forgotPassword-out-0.destination=sentOtpForgotPassword
spring.cloud.stream.bindings.mail-forgotPassword-out-0.content-type=application/json

# Vault Configuration
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=myroot
spring.cloud.vault.scheme=http
spring.cloud.vault.host=${DOCKER_HOST:localhost}
spring.cloud.vault.port=8200
spring.config.import=vault://
spring.cloud.compatibility-verifier.enabled=false

app.api.key=QWErtyuiopaqwer


## ====== CIRCUIT BREAKER ======
#resilience4j.circuitbreaker.instances.keycloakService.slidingWindowSize=5
#resilience4j.circuitbreaker.instances.keycloakService.failureRateThreshold=50
#resilience4j.circuitbreaker.instances.keycloakService.waitDurationInOpenState=5000ms
#resilience4j.circuitbreaker.instances.keycloakService.permittedNumberOfCallsInHalfOpenState=3
#resilience4j.circuitbreaker.instances.keycloakService.automaticTransitionFromOpenToHalfOpenEnabled=true
#
#resilience4j.circuitbreaker.instances.coreBankingService.slidingWindowSize=5
#resilience4j.circuitbreaker.instances.coreBankingService.failureRateThreshold=50
#resilience4j.circuitbreaker.instances.coreBankingService.waitDurationInOpenState=5000ms
#
#resilience4j.circuitbreaker.instances.kafkaService.slidingWindowSize=5
#resilience4j.circuitbreaker.instances.kafkaService.failureRateThreshold=50
#resilience4j.circuitbreaker.instances.kafkaService.waitDurationInOpenState=5000ms
#
#resilience4j.circuitbreaker.instances.kycService.slidingWindowSize=5
#resilience4j.circuitbreaker.instances.kycService.failureRateThreshold=50
#resilience4j.circuitbreaker.instances.kycService.waitDurationInOpenState=5000ms
#
## ====== RETRY CONFIG ======
#resilience4j.retry.instances.keycloakService.maxAttempts=3
#resilience4j.retry.instances.keycloakService.waitDuration=500ms
#resilience4j.retry.instances.keycloakService.retryExceptions[0]=java.util.concurrent.TimeoutException
#
#resilience4j.retry.instances.coreBankingService.maxAttempts=3
#resilience4j.retry.instances.coreBankingService.waitDuration=500ms
#
#resilience4j.retry.instances.kafkaService.maxAttempts=3
#resilience4j.retry.instances.kafkaService.waitDuration=500ms
#resilience4j.retry.instances.kafkaService.retryExceptions[0]=org.springframework.kafka.KafkaException
#
#resilience4j.retry.instances.kycService.maxAttempts=3
#resilience4j.retry.instances.kycService.waitDuration=500ms
#
## ====== TIME LIMITER ======
#resilience4j.timelimiter.instances.keycloakService.timeoutDuration=2s
#resilience4j.timelimiter.instances.keycloakService.cancelRunningFuture=true
#
#resilience4j.timelimiter.instances.kycService.timeoutDuration=2s
#resilience4j.timelimiter.instances.kycService.cancelRunningFuture=true
#
## ====== BULKHEAD ======
#resilience4j.bulkhead.instances.coreBankingService.maxConcurrentCalls=3
#resilience4j.bulkhead.instances.coreBankingService.maxWaitDuration=500ms
#
## ====== ACTUATOR EXPOSURE ======
#management.endpoints.web.exposure.include=health,info,circuitbreakers

