spring.application.name=customer-service
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/customerdb_new?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger Configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

kyc.api.url=https://api.trulioo.com/v1/verify
kyc.api.key=your-api-key-here
# application.properties

# Dubbo Application Configuration
dubbo.application.name=customer_service
dubbo.application.metadata-type=remote
dubbo.application.parameters.dubbo.mapping.cache.file=C:/Users/thienvy/.dubbo/customer-service-cache
dubbo.application.serialization.security.allowlist=file:security/serialize.allowlist
# Dubbo Protocol Configuration
dubbo.protocol.name=dubbo
dubbo.protocol.port=20889
dubbo.application.qos-enable=true
dubbo.application.qos-port=33333
# Dubbo Registry Configuration
dubbo.registry.address=zookeeper://${DOCKER_HOST:localhost}:2181
dubbo.scan.base-packages=com.example.customer_service.service

# ========== MESSAGES / I18N ==========
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.default-locale=en


## ========== JWT ==========
#jwt.expiration=2592000
#jwt.expiration-refresh-token=5184000
#jwt.secretKey=2bBXzdplW1CbCQqvzmHApdmM91XrxbrJqtgUfQJSEWk=

# Keycloak Configuration
keycloak.auth-server-url=http://localhost:8081
keycloak.realm=myrealm
keycloak.resource=customer-service
keycloak.bearer-only=false

# Spring Security JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/myrealm

# Keycloak Admin Client
idp.url=http://localhost:8180
idp.realm=myrealm
idp.client-id=customer-service
idp.client-secret=enzqzDqemWgledxd6qhpeKQKPSTHApN3

# Kafka Basic Configuration
spring.kafka.bootstrap-servers=localhost:9094

spring.kafka.consumer.group-id=customer-service-kafka
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Spring Cloud Stream Configuration
spring.cloud.stream.kafka.binder.brokers=${DOCKER_HOST:localhost}:9094

# Producer: gửi email OTP đăng ký
spring.cloud.stream.bindings.mail-out-0.destination=sentOtpRegister
spring.cloud.stream.bindings.mail-out-0.content-type=application/json

# Producer: gửi email quên mật khẩu  
spring.cloud.stream.bindings.mail-forgotPassword-out-0.destination=sentOtpForgotPassword
spring.cloud.stream.bindings.mail-forgotPassword-out-0.content-type=application/json


management.endpoints.web.exposure.include=health,info,metrics,retries,circuitbreakers
management.endpoint.health.show-details=always

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
core-banking.api.key=asdfghjkl