spring.application.name=loan-service
server.port=9827
# ? Database ?
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/loan_service_db?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10

# ? Hibernate ?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
dubbo.consumer.scope=remote
dubbo.application.name=loan-service
dubbo.protocol.name=dubbo
dubbo.protocol.port=20869
dubbo.application.qos-enable=true
dubbo.application.qos-port=21225
dubbo.registry.address=zookeeper://localhost:2181
dubbo.consumer.timeout=20000
dubbo.scan.base-packages=com.example.loan_service.service
dubbo.consumer.filters=dubboProviderSecurityFilter

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/myrealm
spring.cloud.stream.kafka.binder.brokers=${DOCKER_HOST:localhost}:9094
spring.cloud.stream.bindings.mail-out-0.destination=send-mail-raw

spring.cloud.stream.bindings.mail-out-0.content-type=application/json

core-banking.api-key=a5dde333-b181-406d-8b41-5ae960579488

management.endpoints.web.exposure.include=health,info,metrics,retries,circuitbreakers
management.endpoint.health.show-details=always

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
