# Server configuration
server.port=8085
spring.application.name=cic-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/myrealm

# CIC API configuration
cic.api.url=http://localhost:8090/api/cic
cic.api.key=Mock-API-Key

# Resilience4j Circuit Breaker configuration
resilience4j.circuitbreaker.instances.cicCheck.slidingWindowSize=10
resilience4j.circuitbreaker.instances.cicCheck.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.cicCheck.failureRateThreshold=50
resilience4j.circuitbreaker.instances.cicCheck.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.cicCheck.permittedNumberOfCallsInHalfOpenState=3

# Resilience4j Retry configuration
resilience4j.retry.instances.cicCheck.maxAttempts=3
resilience4j.retry.instances.cicCheck.waitDuration=1s
resilience4j.retry.instances.cicCheck.enableExponentialBackoff=true
resilience4j.retry.instances.cicCheck.exponentialBackoffMultiplier=2

# Logging configuration
logging.level.com.cic.cicservice=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# java -jar wiremock-jre8-standalone-2.35.0.jar --port 8090 --root-dir CIC-MockServer