server:
  port: 8083
  servlet:
    context-path: /corebanking
spring:
  application:
    name: corebanking-service
  datasource:
    url: jdbc:mysql://localhost:3307/coredb
    username: root
    password: 0986341885dai
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


api-key: a5dde333-b181-406d-8b41-5ae960579488
