# Server configuration
server.port=9085
spring.application.name=openingbanking-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/myrealm


openingbanking.api.url=http://localhost:9090/api/openingbanking
openingbanking.api.key=Mock-API-Key

# Resilience4j Circuit Breaker configuration
resilience4j.circuitbreaker.instances.checkIncome.slidingWindowSize=10
resilience4j.circuitbreaker.instances.checkIncome.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.checkIncome.failureRateThreshold=50
resilience4j.circuitbreaker.instances.checkIncome.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.checkIncome.permittedNumberOfCallsInHalfOpenState=3

# Resilience4j Retry configuration
resilience4j.retry.instances.checkIncome.maxAttempts=3
resilience4j.retry.instances.checkIncome.waitDuration=1s
resilience4j.retry.instances.checkIncome.enableExponentialBackoff=true
resilience4j.retry.instances.checkIncome.exponentialBackoffMultiplier=2

# Logging configuration
logging.level.com.cic.cicservice=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# java -jar wiremock-jre8-standalone-2.35.0.jar --port 9090 --root-dir OpeningBanking-MockServer