server:
  port: 8082
  servlet:
    context-path: /account

app:
  api:
    key: QWErtyuiopaqwer
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/myrealm
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename:
      - i18n/messages
    encoding: UTF-8
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${DOCKER_HOST:localhost}:9094
      bindings:
        mail-out-0:
          destination: send-mail-html
          content-type: application/json
  data:
    redis:
      host: localhost
      port: 6379

# Core Banking Service Configuration
core-banking:
  base-url: http://localhost:8083/corebanking

dubbo:
  provider:
    filter: -contextHolderAuthenticationResolverFilter
  consumer:
    filter: -contextHolderAuthenticationResolverFilter
  application:
    name: account-service
    qos-enable: false
    serialize-check-status: WARN
    # hoặc nếu cần thiết (không khuyến nghị cho production):
    # serialize-check-status: DISABLE

    serialize:
      allowlist: com.example.customer_service.exceptions.AppException,java.lang.RuntimeException,java.lang.Exception

  protocol:
    name: dubbo
    port: 20882
    serialization: hessian2

  registry:
    address: zookeeper://localhost:2181

  scan:
    base-packages: com.example.account_service.service


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Enable resilience4j actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,retries,circuitbreakers
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0  # Sample 100% of requests in development
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans